# Generated by Django 6.0.1 on 2026-01-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Expense Tracker', max_length=100)),
                ('site_description', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('footer_text', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
